spring.application.name=recommendation-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=health,info

# Resilience4j Bulkhead
resilience4j.bulkhead.instances.recommendationBulkhead.max-concurrent-calls=5
resilience4j.bulkhead.instances.recommendationBulkhead.max-wait-duration=0

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans