spring.application.name=eureka-server
server.port=8761

# Eureka Server should not register itself as another service in Eureka.
eureka.client.register-with-eureka=false
#Eureka Server doesn't need to fetch a registry from another Eureka server.
eureka.client.fetch-registry=false