spring.application.name=product-service
server.port=8081

#tells Product Service: The Eureka Server is running here
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/circuitbreaker
spring.datasource.username=postgres
spring.datasource.password=0000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info