# =========================================================
# API GATEWAY
# =========================================================

spring.application.name=api-gateway
server.port=8080


# =========================================================
# EUREKA
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# =========================================================
# PRODUCT SERVICE
# =========================================================

spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/products/**


# =========================================================
# INVENTORY SERVICE
# =========================================================

spring.cloud.gateway.server.webmvc.routes[1].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/inventory/**


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


# =========================================================
# CIRCUIT BREAKER
# =========================================================

resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.sliding-window-size=1
resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.permitted-number-of-calls-in-half-open-state=1

resilience4j.circuitbreaker.instances.recommendationCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true


# =========================================================
# TIME LIMITER
# =========================================================

resilience4j.timelimiter.instances.recommendationCircuitBreaker.timeoutDuration=2s
resilience4j.timelimiter.instances.recommendationCircuitBreaker.cancelRunningFuture=true


# =========================================================
# RATE LIMITER
# =========================================================

resilience4j.ratelimiter.instances.gatewayRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.gatewayRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.gatewayRateLimiter.timeout-duration=0


# =========================================================
# BULKHEAD
# =========================================================

resilience4j.bulkhead.instances.recommendationBulkhead.max-concurrent-calls=5
resilience4j.bulkhead.instances.recommendationBulkhead.max-wait-duration=0


# =========================================================
# ZIPKIN / DISTRIBUTED TRACING
# =========================================================

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans